version: '3'
services:
  server:
    build: 
      context: .
    links:
      - db
      - zipkin
    volumes:
      - "${PWD}:/service"
    ports:
      - "8000:8010"
    networks:
      - sanic-network
    environment:
      POSTGRES_SERVICE_DB_NAME: postgres
      POSTGRES_SERVICE_USER: postgres
      POSTGRES_SERVICE_HOST: db
      POSTGRES_SERVICE_PORT: 5432
      ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      ACCESS_CONTROL_ALLOW_HEADERS: "Content-Type"
      ACCESS_CONTROL_ALLOW_METHODS: "POST, PUT, DELETE, GET"
      ZIPKIN_SERVER: 'http://zipkin:9411/api/v1/spans'
      CONSUL_HTTP_ADDR: 'consul1:8500'
      #command: python -m sanic server.app --host=0.0.0.0 --port=8000 --workers=4
    depends_on:
      - "db"
    command: ["python", "-m", "server"]
    #command: ["python", "-m", 'sanic', "service.server.app", "--workers=4", "--port=8000", "--host=0.0.0.0"]

  db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    networks:
      - sanic-network

  zipkin:
    image: "openzipkin/zipkin:2.4.2"
    ports:
      - "9410:9410"
      - "9411:9411"
    networks:
      - sanic-network

  swagger:
    image: "swaggerapi/swagger-ui:v3.0.5"
    links:
      - server
    ports:
      - "8090:8080"
    networks:
      - sanic-network
    environment:
      API_URL: "http://localhost:8000/openapi/spec.json"

  consul1:
    image: "consul:1.1.0"
    networks:
      - sanic-network
    environment: 
      - CONSUL_BIND_INTERFACE:eth0
    # deploy:
    #   placement:
    #     constraints: [node == ms-master]
    ports:
      - "8500:8500"

  consul2:
    image: "consul:1.1.0"
    networks:
      - sanic-network
    depends_on:
      - consul1
    environment: 
      - CONSUL_BIND_INTERFACE:eth0
    command: ["agent", "-dev", "-join=consul1"]

  consul3:
    image: "consul:1.1.0"
    networks:
      - sanic-network
    depends_on:
      - consul1
    environment: 
      - CONSUL_BIND_INTERFACE:eth0
    command: ["agent", "-dev", "-join=consul1"]
  

networks:
  sanic-network:
    driver: bridge

